name: PreComposeSample
options:
  bundleIdPrefix: moe.tlaster
settings:
  DEVELOPMENT_TEAM: N462MKSJ7M
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CODE_SIGN_STYLE: Automatic
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "4"
  SDKROOT: iphoneos
targets:
  PreComposeSample:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    prebuildScripts:
      - script: cd "$SRCROOT" && ./gradlew -i -p . packComposeUikitApplicationForXCode
        name: GradleCompile
    info:
      path: sample/ios/plists/Ios/Info.plist
      properties:
        UILaunchStoryboardName: ""
    sources:
      - "sample/ios/src"
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"